---

dataset:
  name: 'sim_data'
  n_samples: 100
  dim: 2
  batch_size: 10
  class_list: [0, 1, 2, 3, 4]
  fraction: 0.3
  


optimizer:
  max_epochs: 10
  log_interval: 20
  vis_interval: 20
  latent_epochs: 50
  param_epochs: 50
  lrs:
    Z: 1e-2
    param: 1e-2




model:
  lam: 0.2
  K: 2
  rho: 3.0
  omega: 0.5

  H_epochs: 50


  



hydra:
  run:
    dir: ../results/