---

dataset:
  name: 'sim_data'
  n_samples: 1000
  batch_size: 128
  dim: 2
  class_list: [0, 1, 2, 3, 4]
  fraction: 0.3
  


optimizer:
  max_epochs: 10000
  latent_iters: 10
  param_iters: 1
  log_interval: 20
  vis_interval: 20
  lrs:
    Z: 5e-2
    params: 1e-3




model:
  K: 10
  rho: 0.9
  omega: 0.1
  


  



hydra:
  run:
    dir: ../results/